services:
  db:
    image: postgres:15-alpine
    container_name: introducere_vuejs_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: introducere_vue_db
    ports:
      - "5434:5432"
    volumes:
      - introducere_vue_db:/var/lib/postgresql/data

volumes:
  introducere_vue_db:
